apm_user_visitor_security_login:
    pattern:   /login
#    host:     "%domain_apm%"
    defaults:
        _controller: ApmUserBundle:Visitor/Security:login

cdo_user_visitor_security_login:
    pattern:   /login
    host:     "{subdomain}.%domain_apm%"
    defaults:
        _controller: CdoUserBundle:Visitor/Security:login
        subdomain: "abcformation"

apm_user_visitor_security_login_check:
    pattern:   /login_check
    host:     "%domain_apm%"

cdo_user_visitor_security_login_check:
    pattern:   /login_check
    host:     "{subdomain}.%domain_apm%"
    defaults:
        subdomain: "abcformation"

logout:
    pattern:   /logout

apm_user:
    resource: "@ApmUserBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "%domain_apm%"

cdo_user:
    resource: "@CdoUserBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "{subdomain}.%domain_apm%"
    defaults:
        subdomain: "abcformation"

apm_site:
    resource: "@ApmSiteBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "%domain_apm%"

cdo_site:
    resource: "@CdoSiteBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "{subdomain}.%domain_apm%"
    defaults:
        subdomain: "abcformation"

apm_account:
    resource: "@ApmAccountBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "%domain_apm%"

cdo_account:
    resource: "@CdoAccountBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "{subdomain}.%domain_apm%"
