cdo_site:
    resource: "@CdoSiteBundle/Resources/config/routing.yml"
    prefix:   /

cdo_security_login:
    pattern:   /login
    defaults:  { _controller: CdoSecurityBundle:Security:login }

cdo_security_login_check:
    pattern:   /login_check

cdo_security:
    resource: "@CdoSecurityBundle/Resources/config/routing.yml"
    prefix:   /

cdo_user:
    resource: "@CdoUserBundle/Resources/config/routing.yml"
    prefix:   /

apm_account:
    resource: "@ApmAccountBundle/Resources/config/routing.yml"
    prefix:   /apm

cdo_account:
    resource: "@CdoAccountBundle/Resources/config/routing.yml"
    prefix:   /

apm_site:
    resource: "@ApmSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
