security:
    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/master, roles: ROLE_ADMIN }

    providers:
        cdo_provider:
            id: cdo_user.user_provider

    encoders:
        Cdo\UserBundle\Entity\User: sha512
