services:
    cdo_user.user_manager.connection_default:
        class: Cdo\UserBundle\Service\UserManager
        public: true
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @doctrine
            - 'manager_default'
            - %fos_user.model.user.class%

    cdo_user.user_manager.connection_0:
        class: Cdo\UserBundle\Service\UserManager
        public: true
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @doctrine
            - 'manager_0'
            - %fos_user.model.user.class%